"""
BigQuery connector for Maven conversations.

Queries tt-dp-prod.maven.conversations (and optionally joins messages)
to build a transcript DataFrame matching the app's expected columns:
  Date, Text (full transcript), Summary (user_request_summary)

Uses Google ADC — same credential flow as gemini.py, no API keys needed.
"""

import json
import requests
import google.auth
import google.auth.transport.requests
import pandas as pd
from typing import Optional

BQ_PROJECT = "tt-dp-prod"
BQ_QUERY_URL = f"https://bigquery.googleapis.com/bigquery/v2/projects/{BQ_PROJECT}/queries"

CHANNELS = ["chat", "sms", "voice"]


def _get_token() -> str:
    creds, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/cloud-platform"])
    creds.refresh(google.auth.transport.requests.Request())
    return creds.token


def _run_query(sql: str, timeout_ms: int = 60000) -> list[dict]:
    """Execute a BigQuery SQL query and return rows as list of dicts."""
    headers = {
        "Authorization": f"Bearer {_get_token()}",
        "Content-Type": "application/json",
    }
    payload = {
        "query": sql,
        "useLegacySql": False,
        "timeoutMs": timeout_ms,
        "location": "US",
    }
    resp = requests.post(BQ_QUERY_URL, headers=headers, json=payload)
    resp.raise_for_status()
    data = resp.json()

    if not data.get("jobComplete"):
        raise TimeoutError("BigQuery job did not complete within timeout. Try a smaller date range.")

    schema_fields = [f["name"] for f in data.get("schema", {}).get("fields", [])]
    rows = []
    for row in data.get("rows", []):
        rows.append({schema_fields[i]: v["v"] for i, v in enumerate(row["f"])})
    return rows


def fetch_maven_conversations(
    channel: str,
    start_date: str,
    end_date: str,
    escalated_only: bool = False,
    limit: int = 500,
) -> pd.DataFrame:
    """
    Pull Maven conversations from BigQuery.

    Returns a DataFrame with columns: Date, Text, Summary, conversation_id, channel,
    resolution_status, sentiment, was_escalated.

    The 'Text' column is a concatenated transcript built from the messages table.
    'Summary' maps to user_request_summary (already AI-generated by Maven).
    """
    escalation_filter = "AND c.was_actual_escalated = true" if escalated_only else ""
    channel_filter = f"AND c.channel = '{channel}'" if channel != "all" else ""

    # Build full transcript by concatenating messages per conversation
    sql = f"""
WITH msg_concat AS (
    SELECT
        m.conversation_reference_id,
        STRING_AGG(
            CASE
                WHEN m.message_type = 'bot' THEN CONCAT('Bot: ', COALESCE(m.bot_response_text, ''))
                ELSE CONCAT('User: ', COALESCE(m.message_text, ''))
            END,
            '\\n' ORDER BY m.message_index
        ) AS transcript_text
    FROM `tt-dp-prod.maven.messages` m
    WHERE m.created_date BETWEEN '{start_date}' AND '{end_date}'
    GROUP BY m.conversation_reference_id
)
SELECT
    c.conversation_reference_id,
    c.channel,
    c.created_date,
    c.user_request_summary,
    c.resolution_status_summary,
    c.sentiment,
    c.was_actual_escalated,
    c.is_resolution_status_escalated,
    COALESCE(mc.transcript_text, '') AS transcript_text
FROM `tt-dp-prod.maven.conversations` c
LEFT JOIN msg_concat mc ON c.conversation_reference_id = mc.conversation_reference_id
WHERE c.created_date BETWEEN '{start_date}' AND '{end_date}'
  {channel_filter}
  {escalation_filter}
ORDER BY c.created_date DESC
LIMIT {limit}
"""

    rows = _run_query(sql)
    if not rows:
        return pd.DataFrame(columns=["Date", "Text", "Summary", "conversation_id", "channel",
                                     "resolution_status", "sentiment", "was_escalated"])

    df = pd.DataFrame(rows)
    # Map to app's expected column names
    df = df.rename(columns={
        "created_date": "Date",
        "transcript_text": "Text",
        "user_request_summary": "Summary",
        "conversation_reference_id": "conversation_id",
        "resolution_status_summary": "resolution_status",
        "was_actual_escalated": "was_escalated",
    })
    df["Date"] = pd.to_datetime(df["Date"]).dt.date
    return df


def get_channel_counts(start_date: str, end_date: str) -> dict:
    """Quick count by channel to show the user what's available before pulling."""
    sql = f"""
SELECT channel, COUNT(*) as cnt
FROM `tt-dp-prod.maven.conversations`
WHERE created_date BETWEEN '{start_date}' AND '{end_date}'
GROUP BY channel
ORDER BY cnt DESC
"""
    rows = _run_query(sql)
    return {r["channel"]: int(r["cnt"]) for r in rows}
